/**
 * Generated by orval 🍺
 * Do not edit manually.
 * aegis-backend
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';



export type refreshResponse200 = {
  data: void
  status: 200
}

export type refreshResponse400 = {
  data: string
  status: 400
}

export type refreshResponse401 = {
  data: string
  status: 401
}

export type refreshResponse500 = {
  data: string
  status: 500
}

export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponse400 | refreshResponse401 | refreshResponse500) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {




  return `${import.meta.env["VITE_BACKEND_URL"]!}/auth/refresh`
}

export const refresh = async ( options?: RequestInit): Promise<refreshResponse> => {

  const res = await fetch(getRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: refreshResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : undefined
  return { data, status: res.status, headers: res.headers } as refreshResponse
}





export const getRefreshMutationKey = () => ['refresh'] as const;

export const getRefreshMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext> => {

const mutationKey = getRefreshMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refresh>>, void> = () => {


          return  refresh(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshMutationResult = NonNullable<Awaited<ReturnType<typeof refresh>>>

    export type RefreshMutationError = string


    export const useRefresh = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRefreshMutationOptions(options), queryClient);
    }
