/**
 * Generated by orval 🍺
 * Do not edit manually.
 * aegis-backend
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';



export type signOutResponse200 = {
  data: unknown
  status: 200
}

export type signOutResponse500 = {
  data: string
  status: 500
}

export type signOutResponseSuccess = (signOutResponse200) & {
  headers: Headers;
};
export type signOutResponseError = (signOutResponse500) & {
  headers: Headers;
};

export type signOutResponse = (signOutResponseSuccess | signOutResponseError)

export const getSignOutUrl = () => {




  return `${import.meta.env["VITE_BACKEND_URL"]!}/auth/sign-out`
}

export const signOut = async ( options?: RequestInit): Promise<signOutResponse> => {

  const res = await fetch(getSignOutUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: signOutResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as signOutResponse
}





export const getSignOutMutationKey = () => ['signOut'] as const;

export const getSignOutMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,void, TContext> => {

const mutationKey = getSignOutMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signOut>>, void> = () => {


          return  signOut(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignOutMutationResult = NonNullable<Awaited<ReturnType<typeof signOut>>>

    export type SignOutMutationError = string


    export const useSignOut = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signOut>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSignOutMutationOptions(options), queryClient);
    }
