catalogMode: strict
catalog:
  "@types/react": ^19.3.0
  "@types/react-dom": ^19.3.0
  '@vitejs/plugin-react': ^6.1.1
  oxc-transform-react: ^0.149.0
  react: ^19.3.0
  react-dom: ^19.3.0
  typescript: ^7.0.2
